(*
** communication.ebnf for super_zappy in /home/aracthor/programs/projects/hub/super_zappy/doc
** 
** Made by 
** Login   <aracthor@epitech.net>
** 
** Started on  Sat Oct  4 15:57:56 2014 
## Last Update Wed Nov 12 13:53:38 2014 
*)


(* Maccros *)
Maccros	=
GROUNDS_NUMBER	= 18 ;
OBJECTS_NUMBER	= 6 ;
ITEMS_NUMBER	= 0 ;


(* Numeric values *)
Numerics values	=
pos_x		= integer ;
pos_y		= integer ;
height		= integer ;
player_id	= integer ;
team_id		= integer ;
orientation	= '0' | '1' | '2' | '3' ;
ground_enum	= '0' | '1' | '..' | GROUNDS_NUMBER ;
object_enum	= '0' | '1' | '..' | OBJECTS_NUMBER ;
item_enum	= '0' | '1' | '..' | ITEMS_NUMBER ;
item_number	= integer ;
item_discalified= boolean ;
time_unit	= integer ;
equipement	= item_enum ;


(* Strings values *)
Strings values	=
team_name	= string ;
player_name	= string ;


(* Group values *)
Group values	=
inventory	= { ' ', item_enum, ' ', number } ;


(* Server to graphical clients *)
Server to graphical clients =
chunk_description	= "CHK ", pos_x, ' ', pos_y, '\n', { case_description };
case_description	= "CAS ", pos_x, ' ', pos_y, ' ', ground_enum, ' ', height, ' ', item_enum, ' ', item_number, ' ', object_enum, ' ', player_id, '\n' ;
player_description	= "PDC ", player_name, ' ', pos_x, ' ', pos_y, ' ', orientation, ' ', class_name, ' ', team_name, ' ', equipement, inventory, '\n' ;
player_position		= "PPO ", player_name, ' ', pos_x, ' ', pos_y, ' ', orientation, '\n' ;
player_equipement	= "PEQ ", player_name, ' ', equipement, '\n' ;
player_taking		= "PTK ", player_name, ' ', item_enum, '\n' ;
player_putting		= "PPT ", player_name, ' ', item_enum, '\n' ;
team_description	= "TDC ", team_name, ' ', team_discalified, '\n' ;


(* Graphical client questions *)
Graphical client questions =
chunk_ask	= "CHK ", pos_x, ' ', pos_y, '\n' ;
case_ask	= "CAS ", pos_x, ' ', pos_y, '\n' ;
player_ask	= "PDC ", player_id, '\n' ;
team_ask	= "TDC ", team_name, '\n' ;


(* Graphical client answers *)
Graphical client answers =
chunk_ans	= chunk_description ;
case_ans	= case_description ;
player_ans	= player_description ;
team_ans	= team_description ;



(* Connections *)
Connections =
welcome_message	= "WELCOME\n" ;
graphic_message	= "GRAPHIC\n" ;
ia_message	= "TEAM\n" ;
server_kick	= "GET THE FUCK OUT\n" ;


(* Graphical init *)
Graphical init =
island_parameters	= "ISL ", time_unit, ' ', map_longer, ' ', map_larger, '\n' ;
team_presentation	= team_description, { player_description } ;
graphical_init		= island_parameters, { team_presentation } ;

(* Team init *)
Team init =
team_config		= "PRE ", team_name, ' ', population, ' ', wealth, ' ', versatility, ' ', genetic_hardening, ' ', skill_capacity, '\n' ;
class_presentation	= "CLD ", class_name, '\n';
player_presentation	= "PLD ", player_name, ' ', class_name, '\n' ;
team_init		= team_config, { class_presentation }, { player_presentation } ;
